apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  namespace: tekton-builder-ltb-ssp
  name: lab-k8s-docker-builder-run-ltb-ssp
  labels:
    docker-builder: ltb-ssp
spec:
  params:
    - name: git-url
      value: https://github.com/konvergence/self-service-password.git
    - name: image-registry
      value: lab-k8s-harbor.shuttle-cloud.com/library
    - name: image-name
      value: ltb-ssp
    - name: dockerfile-context
      value: ./packaging/docker
    - name: dockerfile-name
      value: Dockerfile
    - name: build-args
      value: build_args.txt
    - name: build-tags
      value: build_tags.txt
    - name: build-log-level
      value: info
      

  pipelineRef:
    params:
      - name: name
        value: image-builder
      - name: namespace
        value: tekton-catalog
      - name: kind
        value: pipeline
    resolver: cluster
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
        status: {}
    - name: git-credentials
      secret:
        secretName: git-basic-auth
    - name: docker-credentials
      secret:
        secretName: lab-k8s-docker-basic-auth